contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('', views.main, name='main'),
    path('contacts/', views.contact_book, name='contact_book'),
    path('add/', views.add_contact, name='add_contact'),
    path('edit/<int:pk>/', views.edit_contact, name='edit_contact'),
    path('delete/<int:pk>/', views.delete_contact, name='delete_contact'),
    path('contact/<int:pk>/', views.contact_detail, name='contact_detail'),
]

files/urls.py
from django.urls import path
from . import views

app_name = 'files'

urlpatterns = [
    path('', views.file_list, name='file_list'),
    path('upload/', views.upload_file, name='upload_file'),
    path('files/download/<int:file_id>/', views.download_file, name='download_file'),
    path('files/view/<int:file_id>/', views.view_file, name='view_file'),
    path('files/delete/<int:file_id>/', views.delete_file, name='delete_file'),
]

forecast/urls.py
from django.urls import path
from . import views

app_name = 'forecast'

urlpatterns = [
    path('', views.get_weather_forecast, name='get_weather_forecast'),
    path('current/', views.get_current_weather, name='get_current_weather'),
]

notes/urls.py
from django.urls import path, re_path
from . import views

app_name = 'notes'

urlpatterns = [
    # path('', views.main, name='main'),
    path('', views.notes, name='notes'),
    path('tag/', views.tag, name='tag'),
    path('note/', views.note, name='note'),
    path('', views.notes, name='notes'),
    # path('notes/', views.notes, name='notes'),
    path('detail/<int:note_id>', views.detail, name='detail'),
    path('delete/<int:note_id>', views.delete_note, name='delete'),
    path('update/<int:note_id>', views.update_note, name='update'),
    path('update_note/<int:note_id>', views.update_note, name='update_note'),
    path('tags/', views.tags, name='tags'),
    path('updatet/<int:tag_id>/', views.update_tag, name='updatet'),
    path('update_tag/<int:tag_id>/', views.update_tag, name='update_tag'),
    # # path('', views.main, name='main'),
    # # re_path('', views.main, name='main'),
]

per_assist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacts.urls')),
    path('notes/', include('notes.urls')),
    path('users/', include('users.urls')),
    path('files/', include('files.urls')),
    path('the_news/', include('the_news.urls')),
    path('forecast/', include('forecast.urls')),
    path('exchange_rates/', include('exchange_rates.urls')),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

the_news/urls.py
from django.urls import path
from . import views

app_name = 'the_news'

urlpatterns = [
    path('', views.news_list, name='news_list'),
    path('<int:pk>/', views.news_detail, name='news_detail'),
    path('fetch-news/', views.fetch_news_view, name='fetch_news'),
]

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

contacts/models.py
from django.db import models
from django.contrib.auth.models import User
from .manager.contact_manager import ContactManager
from phonenumber_field.modelfields import PhoneNumberField


class Contact(models.Model):
    name = models.CharField(max_length=50, null=False)
    surname = models.CharField(max_length=50, null=False)
    email = models.EmailField(max_length=250, null=False, unique=True)
    phone = PhoneNumberField(null=False)
    additional_phone = models.CharField(max_length=20, blank=True, null=True)
    birthday = models.DateField(null=False)
    address = models.CharField(max_length=250, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    additional_info = models.CharField(max_length=100, null=True)

    objects = ContactManager()

    def __str__(self):
        return f"{self.name} {self.surname}"

contacts/forms.py
from django import forms
from .models import Contact
from phonenumber_field.modelfields import PhoneNumberField


class DaysAheadForm(forms.Form):
    days_ahead = forms.IntegerField(
        label='Days Ahead',
        min_value=1,
        required=False,
        help_text='Enter the number of days ahead\
                   to check for upcoming birthdays.'
    )


class ContactSearchForm(forms.Form):
    SEARCH_CHOICES = (
        ('name', 'Name'),
        ('surname', 'Surname'),
        ('phone', 'Phone'),
        ('email', 'Email'),
    )

    find_contact_criteria = forms.ChoiceField(label='Search by',
                                              choices=SEARCH_CHOICES,
                                              required=False)

    find_contact_value = forms.CharField(label='Enter value',
                                         required=False)


class ContactForm(forms.ModelForm):
    birthday = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    phone = PhoneNumberField(region='UA')
    additional_phone = forms.CharField(label='Additional Phone',
                                       required=False)
    additional_info = forms.CharField(required=False)

    class Meta:
        model = Contact
        fields = ['name', 'surname', 'email',
                  'phone', 'birthday', 'address',
                  'additional_phone', 'additional_info']

contacts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Contact
from .forms import DaysAheadForm, ContactSearchForm, ContactForm


def main(request):
    return render(request, 'contacts/index.html')


def contact_book(request):
    contact_list = Contact.objects.all().order_by('-id')

    search_form = ContactSearchForm(request.GET or None)
    if 'find_contact_criteria' in request.GET and 'find_contact_value' in request.GET:
        search_form = ContactSearchForm(request.GET)
        if search_form.is_valid():
            search_criteria = search_form.cleaned_data['find_contact_criteria']
            search_value = search_form.cleaned_data['find_contact_value']
            if search_criteria == 'name':
                contact_list = contact_list.filter(
                    name__icontains=search_value).order_by('-id')
            elif search_criteria == 'surname':
                contact_list = contact_list.filter(
                    surname__icontains=search_value).order_by('-id')
            elif search_criteria == 'phone':
                contact_list = contact_list.filter(
                    phone__icontains=search_value).order_by('-id')
            elif search_criteria == 'email':
                contact_list = contact_list.filter(
                    email__icontains=search_value).order_by('-id')

    days_ahead_form = DaysAheadForm(request.GET or None)
    upcoming_birthdays = get_upcoming_birthdays(7)
    if 'days_ahead' in request.GET:
        days_ahead_form = DaysAheadForm(request.GET)
        if days_ahead_form.is_valid():
            days_ahead = days_ahead_form.cleaned_data['days_ahead']
            contact_list = contact_list.filter(id__in=[contact.id for contact in get_upcoming_birthdays(days_ahead)]).order_by('-id')

    paginator = Paginator(contact_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    request_path = request.path
    return render(request, 'contacts/contacts.html',
                           {'page_obj': page_obj,
                            "upcoming_birthdays": upcoming_birthdays,
                            "request_path": request_path,
                            "days_ahead_form": days_ahead_form,
                            "search_form": search_form})


@login_required
def add_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            if 'additional_phone_checkbox' in request.POST and request.POST[
               'additional_phone_checkbox'] == 'on':
                additional_phone = request.POST.get('additional_phone', None)
                if additional_phone:
                    contact.additional_phone = additional_phone
            form.save()
            return redirect('contacts:contact_book')
    else:
        form = ContactForm()
    return render(request, 'contacts/add_contact.html', {'form': form})


@login_required
def edit_contact(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            form.save()
            return redirect('contacts:contact_book')
    else:
        form = ContactForm(instance=contact)
    return render(request, 'contacts/edit_contact.html', {'form': form})


@login_required
def delete_contact(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    if request.method == 'POST':
        contact.delete()
        return redirect('contacts:contact_book')

    return render(request, 'contacts/confirm_delete.html',
                  {'contact': contact})


def get_upcoming_birthdays(days_ahead):
    if not days_ahead:
        days_ahead = 364
    try:
        days_ahead = int(days_ahead)
    except ValueError:
        days_ahead = 7
    upcoming_birthdays = Contact.objects.get_birthdays_in_days(days_ahead)
    return upcoming_birthdays


def contact_detail(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    return render(request, 'contacts/contact_detail.html',
                           {'contact': contact})

contacts/templates/contacts/add_contact.html
{% extends "contacts/index.html" %}

{% block title %}Add Contact{% endblock %}

{% block content %}
<nav>
    <a href="{% url 'contacts:contact_book' %}">Back</a>
</nav>
<h2>Add New Contact</h2>
<form method="POST">
    {% csrf_token %}
    <div>
        {% for field in form %}
        {% if field.name != 'additional_phone' %}
            <div class="form-field">
                {{ field.label_tag }}
                {{ field }}
                {% if field.errors %}
                    <div class="errors">
                        {% for error in field.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endif %}
    {% endfor %}
        <div>
            <label for="additional_phone_checkbox">Add Additional Phone</label>
            <input type="checkbox" id="additional_phone_checkbox" name="additional_phone_checkbox">
            <div id="additionalPhoneField" class="additional-phone-field">
                {{ form.additional_phone }}
            </div>
        </div>
        <button type="submit">Save</button>
    </div>
</form>
<style>
    .additional-phone-field {
        display: none;
    }

    #additional_phone_checkbox:checked ~ .additional-phone-field {
        display: block;
    }
</style>
<script>
    var checkbox = document.getElementById('additional_phone_checkbox');
    var additionalPhoneField = document.getElementById('additional_phone_field');

    checkbox.addEventListener('change', function() {
        if (checkbox.checked) {
            additionalPhoneField.style.display = 'block';
        } else {
            additionalPhoneField.style.display = 'none';
        }
    });
</script>

{% endblock %}

contacts/templates/contacts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Contacts</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'contacts/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page</a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

contacts/templates/contacts/birthday_list.html
{% extends "contacts/index.html" %}

{% block title %}Birthdays{% endblock %}

{% block content %}
<nav>
    <a href="{% url 'contacts:contact_book' %}">Back</a>
</nav>
    <h1>Find Contacts with Upcoming Birthdays</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Search</button>
    </form>

    {% if page_obj %}
        <h2>Contacts with Birthdays in {{ days_ahead_form.initial.days_ahead }} days:</h2>
        <ul>
        {% for contact in page_obj %}
            <li>{{ contact.name }} {{ contact.surname }} - {{ contact.birthday }}</li>
        {% endfor %}
        </ul>
        {% if page_obj.has_other_pages %}
            <div class="pagination">
                {% if page_obj.has_previous %}
                    <a href="?page=1{% if days_ahead_form.days_ahead.value %}&days_ahead={{ days_ahead_form.days_ahead.value }}{% endif %}">&laquo; First</a>
                    <a href="?page={{ page_obj.previous_page_number }}{% if days_ahead_form.days_ahead.value %}&days_ahead={{ days_ahead_form.days_ahead.value }}{% endif %}">Previous</a>
                {% endif %}
            <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}{% if days_ahead_form.days_ahead.value %}&days_ahead={{ days_ahead_form.days_ahead.value }}{% endif %}">Next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}{% if days_ahead_form.days_ahead.value %}&days_ahead={{ days_ahead_form.days_ahead.value }}{% endif %}">Last &raquo;</a>
                {% endif %}
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

contacts/templates/contacts/contact_detail.html
{% extends "contacts/index.html" %}

{% block title %}Contact Detail{% endblock %}

{% block content %}
<h2>{{ contact.name }} {{ contact.surname }}</h2>
<p>Email: {{ contact.email }}</p>
<p>Phone: {{ contact.phone }}</p>
<p>Birthday: {{ contact.birthday }}</p>
<p>Address: {{ contact.address }}</p>
{% if contact.additional_phone %}
    <p>Additional Phone: {{ contact.additional_phone }}</p>
{% endif %}
{% if contact.additional_info %}
    <p>Additional Info: {{ contact.additional_info }}</p>
{% endif %}
<button type="submit" onclick="window.location.href = '{% url 'contacts:edit_contact' contact.id %}';">Edit</button>
<button type="submit" onclick="window.location.href = '{% url 'contacts:contact_book' %}';">Back to contact list</button>
{% endblock %}

contacts/templates/contacts/contacts.html
{% extends "contacts/index.html" %}

{% block title %}Contact List{% endblock %}

{% block content %}
<style>
        .contact-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            border-bottom: 1px solid #ccc;
        }

        .contact-buttons {
            display: flex;
            gap: 10px;
        }

        .contact-buttons button {
            padding: 5px 10px;
            border: none;
            cursor: pointer;
        }
</style>
<nav>
    <button type="submit" onclick="window.location.href = {% url 'contacts:add_contact' %}">Add new contact</button>
</nav>

<ul>
    {% for contact in page_obj %}
        <li class="contact-item">
            <a href="{% url 'contacts:contact_detail' contact.id %}">{{ contact.name }} {{ contact.surname }}</a> {{ contact.phone }} -- {{ contact.email }}
            <div class="contact-buttons">
            <button type="submit" onclick="window.location.href = '{% url 'contacts:edit_contact' contact.id %}';">Edit</button>
            <form method="post" action="{% url 'contacts:delete_contact' contact.id %}" style="display:inline;">
                {% csrf_token %}
                <button type="submit" onclick="return confirm('Are you sure you want to delete this contact?');">Delete</button>
            </form>
            </div>
        </li>
    {% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

contacts/templates/contacts/edit_contact.html
{% extends "contacts/index.html" %}

{% block title %}Edit Contact{% endblock %}

{% block content %}
<nav>
    <a href="{% url 'contacts:contact_book' %}">Back</a>
</nav>
<h2>Edit Contact</h2>
<form method="POST">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
    </div>
    <div>
        <button type="submit">Save</button>
    </div>
</form>
{% endblock %}

contacts/templates/contacts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Personal assistant</title>
    {% load static %}
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'contacts/main.css' %}">
</head>
<body>

    <div class="container">
        <div class="row header-box">
            <div class="col-md-2">
                <h2>
                    <a href="/" style="text-decoration: none">Personal<br>assistant</a>
                </h2>
            </div>
            <div class="col-md-10">

                <div class="per-assist-menu-container">
                    {% if user.is_authenticated %}
                    <div class="per-assist-menu">
                        <div class="user-menu">
                            <ul>
                                <li><a href="{% url 'contacts:contact_book' %}" role="button">Contacts</a></li>
                                <li><a href="{% url 'notes:notes' %}" role="button">Notes</a></li>
                                <li><a href="{% url 'notes:tags' %}" role="button">Tags</a></li>
                                <li><a href="{% url 'files:file_list' %}" role="button">Files</a></li>
                                <li><a href="{% url 'exchange_rates:exchange_rates' %}" role="button">Exchange rates</a></li>
                                <li><a href="{% url 'the_news:news_list' %}" role="button">News</a></li>
                                <li><a href="{% url 'forecast:get_weather_forecast' %}" role="button">Weather</a></li>
                            </ul>
                        </div>
                        <div class="user-login-menu">
                            <ul>
                                <li>Welcome <b>{{ user.username }}!</b></li>
                                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
                            </ul>
                        </div>
                    </div>
                    {% else %}
                    <div class="per-assist-menu">
                        <ul>
                            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
                        </ul>
                    </div>
                    {% endif %}  
                </div>     

            </div>
        </div>          

        <div class="row">
            
            <div class="col-md-3">

                {% if request_path == "/forecast/current/"%}
                <div class="search_notes">
                    <h4>Select weather for:</h4> 
                    <form method="GET" action="{% url 'forecast:get_current_weather' %}">
                        <select name="location">
                        <option value="50.4501,30.5234" {% if location == 'Kyiv' %}selected{% endif %}>Kyiv</option>
                        <option value="51.5074,-0.1278" {% if location == 'London' %}selected{% endif %}>London</option>
                        <option value="38.8951,-77.0364" {% if location == 'Washington' %}selected{% endif %}>Washington</option>
                        <option value="48.8566,2.3522" {% if location == 'Paris' %}selected{% endif %}>Paris</option>
                        <option value="52.5200,13.4050" {% if location == 'Berlin' %}selected{% endif %}>Berlin</option>
                        <option value="41.9028,12.4964" {% if location == 'Rome' %}selected{% endif %}>Rome</option>
                        <option value="40.4168,-3.7038" {% if location == 'Madrid' %}selected{% endif %}>Madrid</option>
                        </select>
                        <button type="submit">Get weather</button>
                    </form>
                </div>
                {% endif %}

                {% if request_path == "/forecast/"%}
                <div class="search_notes">
                    <h4>Select weather for:</h4>           
                    <form method="GET" action="{% url 'forecast:get_weather_forecast' %}">
                        <select name="location">
                        <option value="50.4501,30.5234" {% if location == 'Kyiv' %}selected{% endif %}>Kyiv</option>
                        <option value="51.5074,-0.1278" {% if location == 'London' %}selected{% endif %}>London</option>
                        <option value="38.8951,-77.0364" {% if location == 'Washington' %}selected{% endif %}>Washington</option>
                        <option value="48.8566,2.3522" {% if location == 'Paris' %}selected{% endif %}>Paris</option>
                        <option value="52.5200,13.4050" {% if location == 'Berlin' %}selected{% endif %}>Berlin</option>
                        <option value="41.9028,12.4964" {% if location == 'Rome' %}selected{% endif %}>Rome</option>
                        <option value="40.4168,-3.7038" {% if location == 'Madrid' %}selected{% endif %}>Madrid</option>
                        </select>
                        <button type="submit">Get weather</button>
                    </form>
                </div>
                {% endif %}

                {% if request_path == "/files/" or request_path == "/files/files/"  %}
                <div class="search_notes">
                    <h4>Files filter</h4>                
                    <form method="get" action="{% url 'files:file_list' %}">
                        <select name="category">
                            <option value="">All categories</option>
                            {% for category in categories %}
                                <option value="{{ category }}" {% if category == request.GET.category %}selected{% endif %}>{{ category }}</option>
                            {% endfor %}
                        </select>
                        <button type="submit">Filter</button>
                    </form>
                </div>
                {% endif %}

                {% if request_path == "/the_news/" or request_path == "/the_news/the_news/"  %}
                <div class="search_notes">
                    <h4>News filter</h4>
                    <form method="get">
                        <select name="categories">
                            <option value="">All categories</option>
                            <option value="general"  {% if selected_category == 'general' %}selected{% endif %}>general</option>
                            <option value="business" {% if selected_category == 'business' %}selected{% endif %}>business</option>
                            <option value="science"  {% if selected_category == 'science' %}selected{% endif %}>science</option>
                            <option value="politics" {% if selected_category == 'politics' %}selected{% endif %}>politics</option>
                            <option value="tech"     {% if selected_category == 'tech' %}selected{% endif %}>tech</option>
                        </select>
                        <button type="submit">Filter</button>
                    </form>
                </div>
                {% endif %}

                {% if request_path == "/notes/" or request_path == "/notes/notes/" %}

                <div class="search_notes">
                    <h4>Search notes</h4>
                    <form method="post">
                        {% csrf_token %}
                        <div>
                            <label for="{{ form.find_note_criteria.id_for_label }}">Search by:</label>
                            {{ form.find_note_criteria }}
                        </div>
                        <div>
                            <label for="{{ form.find_note_value.id_for_label }}">Enter value:</label>
                            {{ form.find_note_value }}
                        </div>
                        <button type="submit">Search</button>
                    </form>
                </div>

                <div class="top_ten_tags">
                    <h4>Sort notes by tags</h4>
                    {% for tag in most_used_tags %}
                        <span class="tag-item">
                            <a class="tag" style="font-size: {{ tag_size_block|slice:forloop.counter|last }}px" href="{% url 'notes:notes' %}?tag_id={{tag.id}}">{{ tag.name }}</a> ({{ tag.num_notes }} notes)
                        </span>
                    {% endfor %}
                </div>
                {% endif %}
                {% if request_path == "/contacts/" %}
                    <div class="upcoming-birthdays">
                        <h4>Upcoming Birthdays</h4>
                        <h5>Birthdays in 7 days</h5>
                        <ul>
                            {% for contact in upcoming_birthdays %}
                                <li>{{ contact.name }} {{ contact.surname }} - {{ contact.birthday }}</li>
                            {% endfor %}
                        </ul>
                        <form method="GET" action="{% url 'contacts:contact_book' %}">
                            {{ days_ahead_form.as_p }}
                            <button type="submit" class="btn btn-primary">Check</button>
                        </form>
                        
                    </div>
                    <div class="search_contacts">
                        <h4>Search Contacts</h4>
                        <form method="get">
                            <div>
                                <label for="{{ search_form.find_contact_criteria.id_for_label }}">Search by:</label>
                                    {{ search_form.find_contact_criteria }}
                            </div>
                            <div>
                                <label for="{{ search_form.find_contact_value.id_for_label }}">Enter value:</label>
                                    {{ search_form.find_contact_value }}
                            </div>
                            <button type="submit">Search</button>
                        </form>
                    </div>
                {% endif %}
            </div>

            <div class="col-md-9">
                
                {% block content %} {% endblock %}

            </div>

        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="copyright">
                Made by <span class="zyte">Pythonic wizards team</span>
            </p>
        </div>
    </footer>

    <div id="gadsf21g"></div><div at-magnifier-wrapper=""><div class="at-theme-light"><div class="at-base notranslate" translate="no"><div class="EuwGd" style="top: 0px; left: 0px;"></div></div></div></div>

</body>
</html>