files/urls.py
from django.urls import path
from . import views

app_name = 'files'

urlpatterns = [
    path('', views.file_list, name='file_list'),
    path('upload/', views.upload_file, name='upload_file'),
    path('files/download/<int:file_id>/', views.download_file, name='download_file'),
    path('files/view/<int:file_id>/', views.view_file, name='view_file'),
    path('files/delete/<int:file_id>/', views.delete_file, name='delete_file'),
]

notes/urls.py
from django.urls import path, re_path
from . import views

app_name = 'notes'

urlpatterns = [
    # path('', views.main, name='main'),
    path('', views.notes, name='notes'),
    path('tag/', views.tag, name='tag'),
    path('note/', views.note, name='note'),
    path('', views.notes, name='notes'),
    # path('notes/', views.notes, name='notes'),
    path('detail/<int:note_id>', views.detail, name='detail'),
    path('delete/<int:note_id>', views.delete_note, name='delete'),
    path('update/<int:note_id>', views.update_note, name='update'),
    path('update_note/<int:note_id>', views.update_note, name='update_note'),
    path('tags/', views.tags, name='tags'),
    path('updatet/<int:tag_id>/', views.update_tag, name='updatet'),
    path('update_tag/<int:tag_id>/', views.update_tag, name='update_tag'),
    # # path('', views.main, name='main'),
    # # re_path('', views.main, name='main'),
]

per_assist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacts.urls')),
    path('notes/', include('notes.urls')),
    path('users/', include('users.urls')),
    path('files/', include('files.urls')),
    path('the_news/', include('the_news.urls')),
    path('forecast/', include('forecast.urls')),
    path('exchange_rates/', include('exchange_rates.urls')),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from django.contrib.auth.models import User

class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]

    def __str__(self):
        return f"{self.name}"


class Note(models.Model):
    title = models.CharField(max_length=70, null=False)
    text = models.CharField(max_length=2500, null=False)
    tags = models.ManyToManyField(Tag)
    # user = models.IntegerField("user_id", null=False)
    user=models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.title}"


notes/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea, ChoiceField, ModelChoiceField, Select, HiddenInput
from django import forms
from .models import Tag, Note


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']


class NoteForm(ModelForm):
    title = CharField(min_length=5, max_length=70, required=True, widget=TextInput())  
    text = CharField(min_length=10, max_length=2500, required=True, widget=Textarea)  

    class Meta:
        model = Note
        # fields = ['note']
        # exclude = ['tags']
        fields = ['title', 'text']
        exclude = ['tags']


class UpdateNoteForm(ModelForm):
    title = CharField(min_length=5, max_length=70, required=True, widget=TextInput())  
    text = CharField(min_length=10, max_length=2500, required=True, widget=Textarea)  

    class Meta:
        model = Note
        fields = ['title', 'text', 'tags', 'user']


class NotesSearchForm(forms.Form):
    SEARCH_CHOICES = (
        ('title', 'Title'),
        ('text', 'Note')
    )

    find_note_criteria = forms.ChoiceField(label='Search by', choices=SEARCH_CHOICES)
    find_note_value = forms.CharField(label='Enter value')        

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import TagForm, NoteForm, UpdateNoteForm, NotesSearchForm
from .models import Tag, Note
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def notes(request, tag_id=None):
    notes = []
    form = NotesSearchForm()
    if request.GET.get('tag_id') != None:
        tag = Tag.objects.get(id=request.GET.get('tag_id'))
        notes = Note.objects.filter(tags=tag, user=request.user).order_by('-id')
    elif request.method == 'POST':
        form = NotesSearchForm(request.POST)
        if form.is_valid():

            search_criteria = form.cleaned_data['find_note_criteria']
            search_value = form.cleaned_data['find_note_value']

            if search_criteria == 'title':
                notes = Note.objects.filter(title__icontains=search_value)
            elif search_criteria == 'text':
                notes = Note.objects.filter(text__icontains=search_value)    
    else:
        notes = Note.objects.filter(user=request.user).order_by('-id')

    notes_with_snippet = []
    for note in notes:
        note_snippet = {
            'id': note.id,
            'title': note.title,
            'text': note.text[:110] + '...',
            'tags': note.tags.all(),
            'user': note.user
        }
        notes_with_snippet.append(note_snippet)

    tag_size_block = list(range(28, 8, -2))
    most_used_tags = get_most_used_tags(request)
    request_path = request.path

    notes = notes_with_snippet

    # Pagination
    paginator = Paginator(notes, 10)
    page_number = request.GET.get('page')
    try:
        notes = paginator.page(page_number)
    except PageNotAnInteger:
        notes = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        notes = paginator.page(paginator.num_pages)

    # context = {
    #     "notes": notes,
    #     "tag_size_block": tag_size_block,
    #     "most_used_tags": most_used_tags,
    #     "request_path": request.path,
    #     'form': form
    # }

    # return render(request, 'notes/notes.html', {"context": context})
    return render(request, 'notes/notes.html', {"notes": notes, "tag_size_block": tag_size_block, "most_used_tags": most_used_tags, "request_path": request_path, "form": form})


@login_required
def tags(request):
    tags = Tag.objects.filter(user=request.user).order_by('-id')
    return render(request, 'notes/tags.html', {"tags": tags })


@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            form.save()
            return redirect(to='notes:tags')
        else:
            return render(request, 'notes/tag.html', {'form': form})

    return render(request, 'notes/tag.html', {'form': TagForm()})


def update_tag(request, tag_id):
    tag = get_object_or_404(Tag, id=tag_id, user=request.user)
    
    if request.method == 'POST':
        form = TagForm(request.POST, instance=tag)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            form.save()
            return redirect(to='notes:tags')
        else:
            return render(request, 'notes/tags.html', {'form': form})
    else:
        form = TagForm(instance=tag)

    return render(request, 'notes/update_tag.html', {'tag': tag, 'form': form})


@login_required
def note(request):
    # tags = Tag.objects.all()
    tags = Tag.objects.filter(user=request.user)

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.user = request.user
            new_note.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)     

            return redirect(to='notes:notes')
        else:
            return render(request, 'notes/note.html', {"tags": tags, 'form': form})

    return render(request, 'notes/note.html', {"tags": tags, 'form': NoteForm()})


@login_required
def detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    # author = get_object_or_404(Author, pk=note.author_id)
    return render(request, 'notes/detail.html', {"note": note})


@login_required
def delete_note(request, note_id):
    Note.objects.filter(pk=note_id, user=request.user).delete()
    return redirect(to='notes:notes')


@login_required
def update_note(request, note_id=None):

    tags = Tag.objects.filter(user=request.user)
    note = get_object_or_404(Note, id=note_id, user=request.user)
    
    if request.method == 'POST':

        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            update_note = form.save(commit=False)
            update_note.user = request.user
            update_note.save()

            note.tags.clear()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                update_note.tags.add(tag)     

            return redirect(to='notes:notes')
    else:
        form = UpdateNoteForm(instance=note)

    return render(request, 'notes/update_note.html', {"tags": tags, "note": note, 'form': form})


def get_most_used_tags(request):
    most_used_tags = Tag.objects.filter(user=request.user).annotate(num_notes=Count('note')).order_by('-num_notes')[:10]
    return most_used_tags

notes/templates/notes/detail.html
{% extends "contacts/index.html" %} {% load extract_tags_detail %} 

{% block content %}


<p><b>{{note.title}}</b>
    {% if user.is_authenticated %}
    <a href="{% url 'notes:update' note.id %}">update</a>
    {% endif %}      
</p>
<p>{{note.text}}</p>
<p>Tags: <small> {{ note.tags.all|format_tags }} </small></p>
{% endblock %}

notes/templates/notes/note.html
{% extends "contacts/index.html" %}

{% block content %}

<form method="POST" action="{% url 'notes:note' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Title:
            {{ form.title }}
        </label>
        <span>{{ form.errors.title }}</span>
    </div>    
    <div style="padding: 10px">
        <label> Note:
            {{ form.text }}
        </label>
        <span>{{ form.errors.text }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

notes/templates/notes/notes.html
{% extends "contacts/index.html" %}

{% block content %}       

<h3>List of notes</h3>

<a href="{% url 'notes:note' %}" role="button">Add new note</a>
<a href="{% url 'notes:tag' %}" role="button">Add new tag</a>

<div class="row">
    <div class="col-md-8">
        {% if rnotes %}
            <div class="received_notes">{{rnotes}}</div>
        {% endif %} 

        {% for note in notes %}
        <div class="note" itemscope="" itemtype="http://schema.org/CreativeWork" style="border:1px solid #7CA3E6; border-radius: 10px; padding: 10px; margin:bottom 20px">
            <div class="title" itemprop="text"><a href="{% url 'notes:detail' note.id %}">{{ note.title }}</a></div>
            <div class="text" itemprop="text">{{ note.text }}</div>
            <div class="tags">
                <meta class="keywords" itemprop="keywords" content="simplicity,understand"> 
                Tags: 
                {% load extract_tags %}
                {% for tag in note.tags|tags %}
                    <a class="tag" href="{% url 'notes:notes' %}?tag_id={{tag.id}}">{{tag.name}}</a>
                {% endfor %}
                {#% if user.is_authenticated and user.is_superuser %#}
                {% if user.is_authenticated %}
                <a href="{% url 'notes:delete' note.id %}" onclick="return confirm('Are you sure you want to delete this note?');" role="button" style="color:rgb(255, 0, 0)"> X </a>
                {% endif %} 
                {% if user.is_authenticated %}
                <a href="{% url 'notes:update' note.id %}" role="button" style="color:rgb(0, 255, 60)"> U </a>
                {% endif %}                 
            </div>
        </div></br>
        {% endfor %}       

        <nav>
            <ul class="pager">
                
                <li class="previous">
                    {% if notes.has_previous %}
                    <a href="?page=1"><span aria-hidden="true">←←</span> First</a>
                    <a href="?page={{ notes.previous_page_number }}"><span aria-hidden="true">←</span> Previous</a>
                    {% endif %}                        
                </li>
                
                <span class="current">
                    Page {{ notes.number }} of {{ notes.paginator.num_pages }}.
                </span>

                <li class="next">
                    {% if notes.has_next %}
                    <a href="?page={{ notes.paginator.num_pages }}">Last <span aria-hidden="true">→→</span></a>
                    <a href="?page={{ notes.next_page_number }}">Next <span aria-hidden="true">→</span></a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
</div>

{% endblock %}

notes/templates/notes/tag.html
{% extends "contacts/index.html" %}

{% block content %}

<form method="POST" action="{% url 'notes:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

notes/templates/notes/tags.html
{% extends "contacts/index.html" %}

{% block content %}

Tags: <a href="{% url 'notes:tag' %}" role="button">Add new tag</a>
{% for tag in tags %}
<div style="width:170px;">
    <div style="margin-bottom: 5px; border:1px solid #7CA3E6; border-radius: 10px; padding: 5px; margin:bottom 20px" class="title" itemprop="text">
        {{ tag.name }} &nbsp;<a href="{% url 'notes:updatet' tag.id %}">edit</a>
    </div>      
</div>
{% endfor %}   

{% endblock %}

notes/templates/notes/update_note.html
{% extends "contacts/index.html" %}

{% block content %}

<form method="POST" action="{% url 'notes:update_note' note.id %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Title:
            {{ form.title }}
        </label>
        <span>{{ form.errors.title }}</span>
    </div>    
    <div style="padding: 10px">
        <label> Note:
            {{ form.text }}
        </label>
        <span>{{ form.errors.text }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <!-- <option value="{{tag.name}}">{{tag.name}}</option> -->
                <option value="{{ tag.name }}" {% if tag in form.instance.tags.all %}selected{% endif %}>{{ tag.name }}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

notes/templates/notes/update_tag.html
{% extends "contacts/index.html" %}

{% block content %}

<form method="POST" action="{% url 'notes:update_tag' tag.id %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Change the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}